//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuppaCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public string product_name { get; set; }
        public string product_type { get; set; }
        public string drink_size { get; set; }
        public string roast { get; set; }
        public Nullable<int> quantity { get; set; }
        public string flavor { get; set; }
        public string milk { get; set; }
        public string customer_email { get; set; }
        public string order_date { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
